### PR TITLE
Add spine chart from creation folder and make first commit

### PR DESCRIPTION
**Pull request by bobhaslett**

### CODE REVIEW

**Comment by sdbernard** [comment]
`const legendAlign = 'hori'; // hori or vert, alignment of the legend
const legendType = 'rect'; // rect, line or circ, geometry of legend marker
`

these aren't used

**Comment by sdbernard** [comment]
```js
const xAxisAlign = 'bottom';
```
This doesn't seem to do anything when changed to 'top'

**Comment by sdbernard** [comment]
```js
const sort = '';// specify 'ascending', 'descending'
```
this doesn't change the order of the bars when changed to descending

**Comment by sdbernard** [comment]
```js
const sortOn = 0;// specify column number to sort on (ignore name column)
```
this doesn't seem to change the sort order

**Comment by sdbernard** [comment]
```html
<title>Bar chart - Visual Vocabulary</title>
```
image

change the <title> in the index.html and the <h1>

**Comment by sdbernard** [comment]
```js
const xAxisHighlight = 0; // sets which tick to highlight on the yAxis
const numTicks = 9;// Number of tick on the uAxis
```

these two aren't used, I guess they need to be added to the left and right xaxis or have individual settings for each axis?

**Comment by sdbernard** [comment]
```js
const showNumberLabels = false;// show numbers on end of bars
```

the code for this to work isn't in the spineChart.js.

**Comment by bobhaslett** [comment]
Those ammendmentsdone now

**Pull request merged**
